### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by timmens** [OpenSourceEconomics/econ-project-templates#107]
## Repository

- [x] Close outdated PRs
- [x] Close outdated / settled issues

### Outer project

- [x] Fix broken badges in README (#108)
- [x] Make sure that  `check_conda_env_creation_and_run_all_checks` runs locally (#108)

### Example 

- [x] Rename paper and presentation files to {{cookiecutter.project_slug}} (#108)
- [x] Move tasks to respective directories (#108)
- [x] Do we need the function `utilities.read_yaml`? (#108)
